name: 'Hello World'
description: 'Greet someone'
author: "Jiaying Lu"
inputs:
  myInput:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: "composite"
  steps:
    - run: python ${{ github.action_path }}/main.py --arg1 ${{ inputs.myInput }}
      shell: bash
