on: [push, pull_request]

name: 🚀 Deploy on push

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        architecture: 'x64'
    - uses: lujiaying/FTP-Deploy-Action-Py3.9@main
      with:
        myInput: Python3.9
